# Prometheus exporter must NOT use push mode according to specs:
# https://opentelemetry.io/docs/reference/specification/metrics/sdk_exporters/prometheus/
# Instead, it pulls (scrapes) metrics data at specific interval
scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]
      - targets: ["otel-collector:8888"]